@host = https://api.helpisblind.se/
###

# @name postAddFundraising

POST {{host}}/fundraisings HTTP/1.1
Content-Type: application/json

{
  "fundraiserSwish": "1112223344",
  "story": "I'm in financial help...",
  "goal": 1000,
  "email": "person@sweden.se"
}

