@host = https://4jof3sttoj.execute-api.eu-west-1.amazonaws.com/prod/
###

# @name postAddFundraising

POST {{host}}/fundraisings HTTP/1.1
Content-Type: application/json

{
  "fundraiserSwish": "1112223344",
  "story": "I'm in financial help...",
  "goal": 1000,
  "email": "person@sweden.se"
}

