@host = https://4jof3sttoj.execute-api.eu-west-1.amazonaws.com/prod
@donationId = 5e890c83da3ffd00089dcde0
###

# @name getDonationById

GET {{host}}/donations/{{donationId}} HTTP/1.1
Content-Type: application/json
