@host = https://4jof3sttoj.execute-api.eu-west-1.amazonaws.com/prod
###

# @name getFundraisingMessagesById

GET {{host}}/fundraisings/messages/5e890c83da3ffd00089dcde0 HTTP/1.1
Content-Type: application/json
