@host = https://apo5qz5j6i.execute-api.eu-west-1.amazonaws.com/prod
###

# @name postAddPledge

POST {{host}}/pledge HTTP/1.1
Content-Type: application/json

{
  "swish": "veryMuchSwish",
  "message": "hepl",
  "goal": 123,
  "email": "example@example.com",
  "expirationDate": 1586027859012,
  "securityCode": "432",
}

