@host = https://api.helpisblind.se
@fundraisingId = 5e89cb2b2c7f030009e534c5
###

# @name postAddDonation

POST {{host}}/donations HTTP/1.1
Content-Type: application/json

{
  "fundraisingId": "{{fundraisingId}}",
  "donatorSwish": "5556667788",
  "message": "I hope you get back on your feet...",
  "amount": 100
}

